//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCoolFormTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCoolFormTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap alien_48x48 {
            get {
                object obj = ResourceManager.GetObject("alien_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alien_egg_48x48 {
            get {
                object obj = ResourceManager.GetObject("alien_egg_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alien_vs_predator_3_48x48 {
            get {
                object obj = ResourceManager.GetObject("alien_vs_predator_3_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bird_32 {
            get {
                object obj = ResourceManager.GetObject("bird_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butterfly_pink_48x48 {
            get {
                object obj = ResourceManager.GetObject("butterfly_pink_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butterfly_purple_48x48 {
            get {
                object obj = ResourceManager.GetObject("butterfly_purple_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap candy_cane {
            get {
                object obj = ResourceManager.GetObject("candy_cane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap candy_canebig {
            get {
                object obj = ResourceManager.GetObject("candy_canebig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Christmas_ornaments {
            get {
                object obj = ResourceManager.GetObject("Christmas_ornaments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cow_32 {
            get {
                object obj = ResourceManager.GetObject("cow_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disc_predator_48x48 {
            get {
                object obj = ResourceManager.GetObject("disc_predator_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_48x48 {
            get {
                object obj = ResourceManager.GetObject("folder_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Funshine_Bear__128x128 {
            get {
                object obj = ResourceManager.GetObject("Funshine_Bear__128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Funshine_Bear_1 {
            get {
                object obj = ResourceManager.GetObject("Funshine_Bear_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GDI_256x256 {
            get {
                object obj = ResourceManager.GetObject("GDI_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap giantapple {
            get {
                object obj = ResourceManager.GetObject("giantapple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap heart_valentine_128x128 {
            get {
                object obj = ResourceManager.GetObject("heart_valentine_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lotus_48x48 {
            get {
                object obj = ResourceManager.GetObject("lotus_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap macIcon1 {
            get {
                object obj = ResourceManager.GetObject("macIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mammooth_1 {
            get {
                object obj = ResourceManager.GetObject("Mammooth_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mammooth_128x128 {
            get {
                object obj = ResourceManager.GetObject("Mammooth_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mydocuments_48x48 {
            get {
                object obj = ResourceManager.GetObject("mydocuments_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mymusic_48x48 {
            get {
                object obj = ResourceManager.GetObject("mymusic_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mypc_48x48 {
            get {
                object obj = ResourceManager.GetObject("mypc_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paisley_6_48x48 {
            get {
                object obj = ResourceManager.GetObject("paisley_6_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panda_32 {
            get {
                object obj = ResourceManager.GetObject("panda_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap penguine_32 {
            get {
                object obj = ResourceManager.GetObject("penguine_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap predator_256x256 {
            get {
                object obj = ResourceManager.GetObject("predator_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap predator_48x48 {
            get {
                object obj = ResourceManager.GetObject("predator_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap purple_flower_48x48 {
            get {
                object obj = ResourceManager.GetObject("purple_flower_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_256x256 {
            get {
                object obj = ResourceManager.GetObject("Quake_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_48x48 {
            get {
                object obj = ResourceManager.GetObject("Quake_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_II_48x48 {
            get {
                object obj = ResourceManager.GetObject("Quake_II_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_III_Arena_48x48 {
            get {
                object obj = ResourceManager.GetObject("Quake_III_Arena_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_IV {
            get {
                object obj = ResourceManager.GetObject("Quake_IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quake_IV_48x48 {
            get {
                object obj = ResourceManager.GetObject("Quake_IV_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rose_128x128 {
            get {
                object obj = ResourceManager.GetObject("rose_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap santa_cap {
            get {
                object obj = ResourceManager.GetObject("santa_cap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snowman {
            get {
                object obj = ResourceManager.GetObject("snowman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Snowman1 {
            get {
                object obj = ResourceManager.GetObject("Snowman1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap snowmansmall {
            get {
                object obj = ResourceManager.GetObject("snowmansmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_48x48 {
            get {
                object obj = ResourceManager.GetObject("symbol_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmas_decoration_green {
            get {
                object obj = ResourceManager.GetObject("xmas_decoration_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmas_decoration_red_ {
            get {
                object obj = ResourceManager.GetObject("xmas_decoration_red_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmas_tree {
            get {
                object obj = ResourceManager.GetObject("xmas_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
